//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyTemplate.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompileErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompileErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HappyTemplate.Resources.CompileErrorMessages", typeof(CompileErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; already exists in the current scope.
        /// </summary>
        internal static string AlreadyExistsInTheCurrentScope_Identifier {
            get {
                return ResourceManager.GetString("AlreadyExistsInTheCurrentScope_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;|%&apos; is not allowed here.
        /// </summary>
        internal static string BeginTemplateStatementBlockNotAllowedHere {
            get {
                return ResourceManager.GetString("BeginTemplateStatementBlockNotAllowedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to break keyword not allowed here.
        /// </summary>
        internal static string BreakNotAllowedHere {
            get {
                return ResourceManager.GetString("BreakNotAllowedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot nest templates within $ ... $.
        /// </summary>
        internal static string CannotNestTemplatesWithinTemplateOutputExpression {
            get {
                return ResourceManager.GetString("CannotNestTemplatesWithinTemplateOutputExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue keyword not allowed here.
        /// </summary>
        internal static string ContinueNotAllowedHere {
            get {
                return ResourceManager.GetString("ContinueNotAllowedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default case specified more than once.
        /// </summary>
        internal static string DefaultCaseSpecifiedMoreThanOnce {
            get {
                return ResourceManager.GetString("DefaultCaseSpecifiedMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value of a lookup may only be specified once.
        /// </summary>
        internal static string DefaultValueMayOnlyBeSpecifiedOnce {
            get {
                return ResourceManager.GetString("DefaultValueMayOnlyBeSpecifiedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated function parameter name &apos;{0}&apos;.
        /// </summary>
        internal static string DuplicateFunctionParameterName_Name {
            get {
                return ResourceManager.GetString("DuplicateFunctionParameterName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate input value &quot;{0}&quot;.
        /// </summary>
        internal static string DuplicateInputValue_Value {
            get {
                return ResourceManager.GetString("DuplicateInputValue_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |&gt; is not allowed here.
        /// </summary>
        internal static string EndTemplateNotAllowedHere {
            get {
                return ResourceManager.GetString("EndTemplateNotAllowedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;%|&apos; not allowed here.
        /// </summary>
        internal static string EndTemplateStatementBlockNotAllowedHere {
            get {
                return ResourceManager.GetString("EndTemplateStatementBlockNotAllowedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &quot;{0}&quot; but encountered &quot;{1}&quot;.
        /// </summary>
        internal static string Expected_Expected_Actual {
            get {
                return ResourceManager.GetString("Expected_Expected_Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected operator.
        /// </summary>
        internal static string ExpectedOperator {
            get {
                return ResourceManager.GetString("ExpectedOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; already defined.
        /// </summary>
        internal static string FunctionAlreadyDefined_FuntionName {
            get {
                return ResourceManager.GetString("FunctionAlreadyDefined_FuntionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character: {0} (0x{1:X4}).
        /// </summary>
        internal static string InvalidCharacter_Character_AsciiCode {
            get {
                return ResourceManager.GetString("InvalidCharacter_Character_AsciiCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid context for assignment operator.
        /// </summary>
        internal static string InvalidContextForAssignmentOperator {
            get {
                return ResourceManager.GetString("InvalidContextForAssignmentOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence &quot;\{0}&quot;.
        /// </summary>
        internal static string InvalidEscapeSequence_InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidEscapeSequence_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value on left side of assignment operator.
        /// </summary>
        internal static string InvalidLValueForAssignment {
            get {
                return ResourceManager.GetString("InvalidLValueForAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literal characters must be one character long.
        /// </summary>
        internal static string LiteralCharsMustBeOneCharLong {
            get {
                return ResourceManager.GetString("LiteralCharsMustBeOneCharLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched &quot;)&quot;.
        /// </summary>
        internal static string MismatchedCloseParen {
            get {
                return ResourceManager.GetString("MismatchedCloseParen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched &quot;|&gt;&quot;.
        /// </summary>
        internal static string MismatchedEndVerbatim {
            get {
                return ResourceManager.GetString("MismatchedEndVerbatim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched &quot;(&quot;.
        /// </summary>
        internal static string MismatchedOpenParen {
            get {
                return ResourceManager.GetString("MismatchedOpenParen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched &apos;$&apos;.
        /// </summary>
        internal static string MismatchedVerbatimOutputExpressionDelimiter {
            get {
                return ResourceManager.GetString("MismatchedVerbatimOutputExpressionDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multipart identifier not allowed in this context.
        /// </summary>
        internal static string MultipartIdentiferNotAllowedInThisContext {
            get {
                return ResourceManager.GetString("MultipartIdentiferNotAllowedInThisContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newline in string literal.
        /// </summary>
        internal static string NewLineInLiteralString {
            get {
                return ResourceManager.GetString("NewLineInLiteralString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a binary operator.
        /// </summary>
        internal static string OperatorIsNotBinary_Operator {
            get {
                return ResourceManager.GetString("OperatorIsNotBinary_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a unary operator.
        /// </summary>
        internal static string OperatorIsNotUnary_Operator {
            get {
                return ResourceManager.GetString("OperatorIsNotUnary_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch case missing &quot;break&quot;.
        /// </summary>
        internal static string SwitchCaseMissingBreak {
            get {
                return ResourceManager.GetString("SwitchCaseMissingBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in expression.
        /// </summary>
        internal static string SyntaxErrorInExpression {
            get {
                return ResourceManager.GetString("SyntaxErrorInExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many characters in hex literal.
        /// </summary>
        internal static string TooManyCharactersInHexLiteral {
            get {
                return ResourceManager.GetString("TooManyCharactersInHexLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was not defined.
        /// </summary>
        internal static string UndefinedVariable_Identifier {
            get {
                return ResourceManager.GetString("UndefinedVariable_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of input.
        /// </summary>
        internal static string UnexpectedEndOfInput {
            get {
                return ResourceManager.GetString("UnexpectedEndOfInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of input while parsing section starting at this location.
        /// </summary>
        internal static string UnexpectedEndOfInputWhileParsingSection {
            get {
                return ResourceManager.GetString("UnexpectedEndOfInputWhileParsingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token &quot;{0}&quot;.
        /// </summary>
        internal static string UnexpectedToken_TokenText {
            get {
                return ResourceManager.GetString("UnexpectedToken_TokenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment &apos;{0}&apos; of &apos;{1}&apos; does not evaluate to a namespace.
        /// </summary>
        internal static string UseStatementDoesNotEvaluateToANamespace_Segment_Namespace {
            get {
                return ResourceManager.GetString("UseStatementDoesNotEvaluateToANamespace_Segment_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; already defined.
        /// </summary>
        internal static string VariableAlreadyDefined_Name {
            get {
                return ResourceManager.GetString("VariableAlreadyDefined_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; is used by another variable defined within the loop&apos;s scope.
        /// </summary>
        internal static string VariableOfSameNameDefinedInForLoopScope_Name {
            get {
                return ResourceManager.GetString("VariableOfSameNameDefinedInForLoopScope_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;$&apos; not allowed here.
        /// </summary>
        internal static string VerbatimOutputExpressionDelimiterNotAllowedHere {
            get {
                return ResourceManager.GetString("VerbatimOutputExpressionDelimiterNotAllowedHere", resourceCulture);
            }
        }
    }
}
