//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyTemplate.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RuntimeMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RuntimeMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HappyTemplate.Resources.RuntimeMessages", typeof(RuntimeMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform &apos;get&apos; operation on method &apos;{0}&apos;.
        /// </summary>
        internal static string CannotGetValueOfMethod_MethodName {
            get {
                return ResourceManager.GetString("CannotGetValueOfMethod_MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform &apos;set&apos; operation on method &apos;{0}&apos;.
        /// </summary>
        internal static string CannotSetValueOfMethod_MethodName {
            get {
                return ResourceManager.GetString("CannotSetValueOfMethod_MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First argument of new() must be an instance of System.Type.
        /// </summary>
        internal static string FirstArgumentToNewMustBeInstanceOfSystemType {
            get {
                return ResourceManager.GetString("FirstArgumentToNewMustBeInstanceOfSystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid literal &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidLiteral_Text {
            get {
                return ResourceManager.GetString("InvalidLiteral_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; on type &apos;{1}&apos; is not invokable.
        /// </summary>
        internal static string MemberIsNotInvokable_MemberNameTypeName {
            get {
                return ResourceManager.GetString("MemberIsNotInvokable_MemberNameTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No constructors were found for {0}.
        /// </summary>
        internal static string NoConstructorsFound_TypeName {
            get {
                return ResourceManager.GetString("NoConstructorsFound_TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No public method named &apos;{0}&apos; exists on type &apos;{1}&apos;.
        /// </summary>
        internal static string PublicMethodDoesNotExist_Method_Type {
            get {
                return ResourceManager.GetString("PublicMethodDoesNotExist_Method_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence step must be a positive value.
        /// </summary>
        internal static string SequenceStepMustBePositive {
            get {
                return ResourceManager.GetString("SequenceStepMustBePositive", resourceCulture);
            }
        }
    }
}
