//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Happy.ScriptEngine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MiscMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Happy.ScriptEngine.Resources.MiscMessages", typeof(MiscMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an identifier.
        /// </summary>
        internal static string AnIdentifier {
            get {
                return ResourceManager.GetString("AnIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , or }.
        /// </summary>
        internal static string CommaOrCloseBrace {
            get {
                return ResourceManager.GetString("CommaOrCloseBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , or ].
        /// </summary>
        internal static string CommaOrCloseBracket {
            get {
                return ResourceManager.GetString("CommaOrCloseBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , or ).
        /// </summary>
        internal static string CommaOrCloseParen {
            get {
                return ResourceManager.GetString("CommaOrCloseParen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not instantiate built-in function class &quot;{0}&quot;.
        /// </summary>
        internal static string CouldNotInstantiateBuiltinFunction_Name {
            get {
                return ResourceManager.GetString("CouldNotInstantiateBuiltinFunction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two or more classes inheriting from BuiltInFunctionBase claim to have the same name:  &quot;{0}&quot;..
        /// </summary>
        internal static string DuplicateBuiltInFunctionName_Name {
            get {
                return ResourceManager.GetString("DuplicateBuiltInFunctionName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;eof&gt;.
        /// </summary>
        internal static string EndOfInput {
            get {
                return ResourceManager.GetString("EndOfInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identifier or literal string.
        /// </summary>
        internal static string IdentifierOrLiteralString {
            get {
                return ResourceManager.GetString("IdentifierOrLiteralString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid character.
        /// </summary>
        internal static string InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert the value to &quot;{0}&quot; because that is not a primitive type.
        /// </summary>
        internal static string IsNotPrimitive_Type {
            get {
                return ResourceManager.GetString("IsNotPrimitive_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to literal string.
        /// </summary>
        internal static string LiteralString {
            get {
                return ResourceManager.GetString("LiteralString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conversion exists between &quot;{0}&quot; and &quot;{1}&quot;.
        /// </summary>
        internal static string NoConversionExists_FromType_ToType {
            get {
                return ResourceManager.GetString("NoConversionExists_FromType_ToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { or &lt;|.
        /// </summary>
        internal static string OpenBraceOrBeginTemplate {
            get {
                return ResourceManager.GetString("OpenBraceOrBeginTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation &quot;{0}&quot; failed..
        /// </summary>
        internal static string OperationFailed_Operation {
            get {
                return ResourceManager.GetString("OperationFailed_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter identifier.
        /// </summary>
        internal static string ParameterIdentifier {
            get {
                return ResourceManager.GetString("ParameterIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template identifier.
        /// </summary>
        internal static string TemplateIdentifier {
            get {
                return ResourceManager.GetString("TemplateIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value to be converted is not of a primitive type.
        /// </summary>
        internal static string ValueToConvertIsNotPrimitive {
            get {
                return ResourceManager.GetString("ValueToConvertIsNotPrimitive", resourceCulture);
            }
        }
    }
}
