/**************************************************************************** 
 * Copyright 2012 David Lurton
 * This Source Code Form is subject to the terms of the Mozilla Public 
 * License, v. 2.0. If a copy of the MPL was not distributed with this file, 
 * You can obtain one at http://mozilla.org/MPL/2.0/.
 ****************************************************************************/

namespace Happy.ScriptEngine.Compiler
{
	public enum HappyTokenKind
	{
		Verbatim,
		Identifier,
		Bang,
		Comma,
		LiteralString,
		LiteralDecimalInt32,
		LiteralHexInt32,
		LiteralHexInt64,
		LiteralDouble,
		LiteralChar,
		LiteralBool,
		LiteralNull,
		KeywordIf,
		KeywordElse,
		KeywordLookup,
		KeywordDefault,
		KeywordCase,
		KeywordFunction,
		KeywordIn,
		KeywordWhile,
		KeywordFor,
		KeywordBetween,
		KeywordWhere,
		KeywordReturn,
		KeywordDef,	
		KeywordLoad,
		KeywordUse,
		KeywordNew,
		KeywordContinue,
		KeywordBreak,
		KeywordSwitch,
		OpenBrace,
		CloseBrace,
		EndOfInput,
		InvalidCharacter,
		OpenVerbatim,
		CloseVerbatim,
		EndOfStatement,
		OperatorOpenParen,
		OperatorCloseParen,
		OperatorOpenBracket,
		OperatorCloseBracket,
		OperatorAssign,
		OperatorAdd,
		OperatorSubtract,
		OperatorDivide,
		OperatorMultiply,
		OperatorMod,
		OperatorEqual,
		OperatorNotEqual,
		OperatorGreaterThan,
		OperatorLessThan,
		OperatorGreaterThanOrEqual,
		OperatorLessThanOrEqual,
		OperatorXor,
		OperatorLogicalAnd,
		OperatorBitwiseAnd,
		OperatorLogicalOr,
		OperatorDot,
		UnaryOperatorNot,
		Output,
		OperatorBitwiseOr,
		BeginTemplate,
		EndTemplate,
		VerbatimOutputExpressionDelimiter,
		Colon,
	}
}

